version: "3.9"
services:
  dev-db:
    image: "postgres:13"
    container_name: dev-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - dev_vm

volumes:
  database:

networks:
  dev_vm:
